### ISSUE TITLE
Informationsfehler in tesla.md

### ISSUE THREAD

**Issue by Sensei-Ninja** [hilbix/tino#1]
Moin tino,

ich habe dich heute über ein heise Kommentar (TCP SACK PANIC Forum) gefunden und mir hier bereits viele deiner Denkanstöße durchgelesen. 
Als allererstes muss ich sagen: Chapeau! And Well done! Deine Denkweisen die ich bis jetzt gelesen habe sind bisher sehr gut durchdacht und auf eine kritische aber informationsreiche Weise niedergeschrieben. Musste oftmals schmunzeln und ich sollte meine denkweise in manchen Themen wohl noch einmal mehr überdenken. Aber danke für die Denkanstöße.

Nun zum eigentlichen Thema: 
Du hast geschrieben 
>Das günstigste Modell 3 von Tesla kostet deutlich über 30 kEUR

Das günstigste Modell "Tesla 3" kostet sogar deutlich über 40k (in der USA).
Die 30k sind nur **theoretisch** für die **minimalste Grundausstattung**. Tesla baut aber kein Tesla 3 für 30k, da  es sich für Tesla nicht rentiert. Bisher tun sie es noch nicht. Das 30k Auto soll kommen, allerdings sind die 30k nur in der USA. Aber zum aktuellen Zeitpunkt kostet der Tesla 3 in Deutschland knapp 45kEur, weil Tesla wie gesagt noch kein 3 in der Grundaustattung baut. Man wird bisher deshalb als Käufer/Kunde von Tesla verpflichtet ein paar teure Zusatzpakete einzukaufen. Noch ein Mindfuck mehr ;-)

Das Model 3 kostet aktuell je nach Batteriestärke und Extras um die 60.000 Euro. Die Preise in den USA sind bei allen drei Fahrzeugen niedriger, trotzdem kostete die günstigste Variante des Model 3 auch in Amerika bisher mehr als 40.000 Dollar. 

Hinzu kommen für den deutschen Markt Mwst, außerdem Transportkosten und Zollgebühren - also kann man schon mal mit min. 50kEur für die minimalste Ausstattung rechnen.

Gruß Sensei.

P.S: Ich habe für meinen Beitrag verscheidene Quellen durchleuchtet und miteinander verglichen.

**Comment by hilbix** [comment]
Hallo @Sensei-Ninja,

danke für den Kommentar.  Es geht um folgenden Link:

https://github.com/hilbix/tino/blob/622d367917d5360e8738717407a31015c97eb2b4/hirnschiss/tesla.md#L43

Mit den 30 kEUR wollte ich nicht ausdrücken, dass es einen Tesla schon für 30kEUR gibt.
Denn mir ist diese Situation sehr wohl bewusst, deshalb steht da auch "deutlich über".

Allerdings rechne ich einerseits damit, dass Tesla irgendwann doch mal die Preise senken könnte.  Dann möchte ich die Texte nich nochmals redigieren müssen.

Andererseits rechne ich lieber immer sehr konservativ beim argumentieren.  Tesla ist ein sehr emotionales Thema.  Ich möchte mich nicht mit irgendwelchen Fanboys auseinandersetzen müssen, nur weil ich irgendeinen Wert etwas knapp angegeben habe oder dies irgendwelchen Hypotheken auf die Zukunft (Aussagen von Elon Musk, die noch nicht der Realität entsprechen) widerspricht.

In genau diesem Fall hätte ich so genau die Argumente, die Du mir geschrieben hast ;)

HTH, deshalb wontfix und closed.

-Tino
PS: Seufz,  leider gibt es keinen einfachen Weg, einen Permalink auf ein Markdown zu legen.  Siehe #3
