### ISSUE TITLE
Fehlschläge in der Forschung (Hirnschiss tesla.md)

### ISSUE THREAD

**Issue by Sensei-Ninja** [hilbix/tino#2]
Zu deinem weiter unten genannten Kommentar mit den Fehlschlägen in der Forschung ist mir noch ein (sehr hilfsreicher) Fehlschlag/Unfall eingefallen. Ein Unfall der noch viele Menschen- und Tierleben retten wird :1st_place_medal: 

> Eigentlich sollte Ernst Krendlinger bei seinem Arbeitgeber ein Rezept für Wachs geringfügig modifizieren. Doch irgendetwas lief gründlich schief. Produziert wurden zehn Tonnen einer faserigen Substanz, die an Watte erinnerten. Der Chemiker reagierte. Machte aus der Fehlproduktion ein Erfolgsrezept.

>Die Erfindung der Wachswolle war eher ein Zufall als gezielte Forschung. Bei der Einstellung einer Maschine vertauschte ein Mitarbeiter Werte und die Maschine lief so unbeobachtet über Nacht. Erst am nächsten Morgen stellte man die Fehleinstellungen fest, zudem war die Maschine mit feinen Wachsfasern überzogen. Man untersuchte diese Wachsfasern und entwickelte daraus das Deurex Pure

"Bei diesem Ölbindemittel handelt es sich um ein spezielles Wachs, das Öl aufsaugt, Wasser aber nicht. "

https://de.wikipedia.org/wiki/Wachswolle
https://www.youtube.com/results?search_query=deurex+pure
https://www.ingenieur.de/technik/fachbereiche/umwelt/zauberwatte-oelpest-wie-panne-glorreiche-erfindung/
https://www.tas-hochwasserschutz.de/produkte/deurex-pure-%C3%B6lbindemittel/

**Comment by hilbix** [comment]
https://github.com/hilbix/tino/blob/622d367917d5360e8738717407a31015c97eb2b4/hirnschiss/tesla.md#L340-L341

Habe ich dazugenommen, danke.

https://github.com/hilbix/tino/commit/9d2fd5b083771b9d5e4dabec50225b2bbea2b27d
